### ISSUE TITLE
stimulus codes for noise sweeps incorrect

### ISSUE THREAD

**Issue by dyf** [AllenInstitute/allensdk.ipfx#51]
https://github.com/AllenInstitute/allensdk.ipfx/blob/087789276869fffd02a6f2486acf84b9100b2312/allensdk/ipfx/nwb_data_reader.py#L59

This code is truncating part of the noise protocol description.  It's producing this:

`C1NSSEED`

When it should be producing this:

`C1NSSEED_1150112` or `C1NSSEED_2150112`

Update this string parsing to handle this correct (and not break for other stimulus types).

**Comment by sgratiy** [comment]
Resolved
